### ISSUE TITLE
Use unique tmp file for changelog

### ISSUE THREAD

**Issue by jkrems** [EndangeredMassa/npub#22]
Just wanted to publish two libraries in two different terminal windows and discovered that you really should not do that with npub...

**Comment by khoomeister** [comment]
What happens?

**Comment by jkrems** [comment]
It will write the changelog to the tmp file, open it in your editor, and then the other `npub` instance will overwrite the file. And you end up with a bunch of warnings in your editor (hopefully) about how the file changed under your feet. At which point your best bet is to `:cq` your way out of both publish runs.
