### ISSUE TITLE
Reinstall node_modules before publish

### ISSUE THREAD

**Issue by jkrems** [EndangeredMassa/npub#24]
It would be great if npub would enforce a clean install of `node_modules` at the very beginning (maybe as an opt-in config in package.json?). The installation should use the registry in `publishConfig` by default.

##### Background

Right now we have the following in all our `package.json` scripts:

```
    "setup": "rm -rf node_modules && npm install --registry ${npm_package_publishConfig_registry}",
    "release-patch": "npm run setup && npub publish patch",
    "release-minor": "npm run setup && npub publish minor",
    "release-major": "npm run setup && npub publish major"
```

It would be great if we could switch to just running `npub publish patch` and be done with it. :)

**Comment by EndangeredMassa** [comment]
Sounds good. I'm fine defaulting this behavior and using a config option to turn it off if you want. Maybe `cleanInstallModules` or something.
