### ISSUE TITLE
Better `isClean` check

### ISSUE THREAD

**Issue by jkrems** [EndangeredMassa/npub#28]
https://github.com/EndangeredMassa/npub/blob/14c6569e95cf7a683335d4877e9f00260c44648d/src/git.coffee#L10-L14

The better check is:

* Run `git status --untracked-files=all --porcelain`
* Make sure the output is empty
* If not, the output contains all individual files that were modified, deleted, or added

**Comment by EndangeredMassa** [comment]
To simplify this to an exit code, how about `[[ -n $(git status --untracked-files=all --porcelain) ]] && exit 1 || exit 0`?

**Comment by jkrems** [comment]
`[[ -z $(git status --untracked-files=all --porcelain) ]]`? Though I really think printing out the list of files as part of a nice error message might be helpful.

**Comment by EndangeredMassa** [comment]
That's true. We should print out the list.
