### ISSUE TITLE
Separate release and publish

### ISSUE THREAD

**Issue by jkrems** [EndangeredMassa/npub#41]
For many of my open source packages I switched to npm [deploys via travis](http://docs.travis-ci.com/user/deployment/npm/). That simplifies npm access rights and ensures that the released version did in fact pass on CI.

It would be great if npub would allow to just manage the release commits (changelog change, tagging) and pushing them to the origin and make the `npm publish` step optional.

**Comment by EndangeredMassa** [comment]
Sounds fine to me!

**Comment by EndangeredMassa** [comment]
Tracking in https://github.com/EndangeredMassa/npub/pull/42
