### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by ghost** [EndangeredMassa/npub#45]
It seems like "npm version" replaces much of the functionality in npub except for the CHANGELOG & license header checks, which could appropriately be handled in scripts.

**Comment by EndangeredMassa** [comment]
`npm version` does do some of the same things, but we want to be able to have more control over the precise order of those steps. It also does (and plans to do) much more.

If you'd rather use `npm version` and write some scripts to do the other things, feel free. However, a single tool to handle all of that is preferable to me, at least.
